// Points the mobile app at the hosted stack or back at the local one.
//   pnpm mobile:env hosted   → writes apps/mobile/.env.local (overrides .env) from .env.hosted
//   pnpm mobile:env local    → removes it, so apps/mobile/.env (local Supabase + dev auto-login) applies
// Then restart Expo with a clean cache: pnpm --filter @octonote/mobile start --lan --clear
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";

const target = process.argv[2];
const root = new URL("../", import.meta.url);
const out = new URL("apps/mobile/.env.local", root);

if (target === "local") {
  if (existsSync(out)) rmSync(out);
  console.log("Mobile → local stack (apps/mobile/.env). Restart Expo with --clear.");
  process.exit(0);
}
if (target !== "hosted") {
  console.error("Usage: pnpm mobile:env hosted|local");
  process.exit(1);
}

const hosted = Object.fromEntries(
  readFileSync(new URL(".env.hosted", root), "utf8")
    .split("\n")
    .filter((l) => /^[A-Z_]+=/.test(l))
    .map((l) => [l.slice(0, l.indexOf("=")), l.slice(l.indexOf("=") + 1)]),
);
const need = ["SUPABASE_URL", "SUPABASE_ANON_KEY", "API_URL", "WEB_URL"];
const missing = need.filter((k) => !hosted[k]);
if (missing.length) {
  console.error(`.env.hosted is missing: ${missing.join(", ")}`);
  process.exit(1);
}
writeFileSync(
  out,
  [
    "# Generated by `pnpm mobile:env hosted` — the hosted Supabase/API/web. Public values only.",
    `EXPO_PUBLIC_SUPABASE_URL=${hosted.SUPABASE_URL}`,
    `EXPO_PUBLIC_SUPABASE_ANON_KEY=${hosted.SUPABASE_ANON_KEY}`,
    `EXPO_PUBLIC_API_URL=${hosted.API_URL}`,
    `EXPO_PUBLIC_WEB_URL=${hosted.WEB_URL}`,
    // No dev user exists on the hosted project: sign in with an emailed code.
    "EXPO_PUBLIC_DEV_AUTO_LOGIN=false",
    "",
  ].join("\n"),
);
console.log("Mobile → hosted stack (apps/mobile/.env.local). Restart Expo with --clear.");
